SUCCESSFUL = 'SUCCESSFUL'
NOT_BALANCE = 'NOT_BALANCE'
NOT_CONNECT_WM = 'NOT_CONNECT_WM'
NOT_WM = 'NOT_WM'
NOT_WATER = 'NOT_WATER'
WM_BUSY = 'WM_BUSY'
USER_BUSY = 'USER_BUSY'
USER_NOT_BUSY = 'USER_NOT_BUSY'

NOT_SUCH_USER = 'NOT_SUCH_USER'

LINKED = 'linked'
CONNECT_TO_WM = 'connect'
DISCONNECT_FROM_WM = 'disconnect'